[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = skip
disable_error_code = arg-type, assignment, no-untyped-def, no-untyped-call, no-any-return, type-arg, return-value, valid-type, misc
