"""Stable domain-event routing keys."""

USER_CREATED = "user.created"
USER_UPDATED = "user.updated"
CHAT_CREATED = "chat.created"
CHAT_DELETED = "chat.deleted"
MESSAGE_RECEIVED = "message.received"
MESSAGE_STORED = "message.stored"
MESSAGE_FAILED = "message.failed"
AI_RESPONSE_GENERATED = "message.generated"
INTEGRATION_CONNECTED = "integration.connected"
INTEGRATION_DISCONNECTED = "integration.disconnected"
INTEGRATION_SYNCED = "integration.synced"
INTEGRATION_EXPIRED = "integration.expired"
USER_LOGGED_IN = "auth.login"
USER_LOGGED_OUT = "auth.logout"
TOKEN_REFRESHED = "auth.refreshed"
PASSWORD_CHANGED = "auth.password_changed"
MEMORY_STORED = "memory.stored"
PLUGIN_REGISTERED = "plugin.registered"
